name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Cache VS Code test binary
      uses: actions/cache@v3
      with:
        path: .vscode-test
        key: ${{ runner.os }}-vscode-${{ hashFiles('package.json') }}
    - run: npm ci
    - run: npm run lint
    - run: npm run compile
    - name: Install Xvfb (for headless VS Code testing)
      run: sudo apt-get install -y xvfb
    - name: Run tests with Xvfb
      run: npm run test:ci
    - name: Package Extension
      run: npm run package
    
    - name: Get VSIX filename
      id: get_vsix
      run: echo "VSIX_PATH=$(ls *.vsix)" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.get_vsix.outputs.VSIX_PATH }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true